{{- if .Values.passwordEncryption.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "redisinsight.fullname" . }}-encryption
  labels:
    {{- include "redisinsight.labels" . | nindent 4 }}
type: Opaque
data:
  encryptionKey: {{ .Values.passwordEncryption.key | default (randAlphaNum 32) | b64enc }}
{{- end }} 