# Simple example with only required fields
clustersSetup:
  enabled: true
  redisClusters:
    # Minimal configuration with only required fields
    - name: minimal-cluster
      host: redis-minimal.example.com
      port: 6379
    
    # Configuration with password and optional fields
    - name: standard-cluster
      host: redis-standard.example.com
      port: 6379
      password: "secure-password"
      tls: false
      db: 0 