apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "redisinsight.fullname" . }}
  labels:
    {{- include "redisinsight.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  {{- if .Values.persistence.enabled }}
  strategy:
    type: Recreate
  {{- end }}
  selector:
    matchLabels:
      {{- include "redisinsight.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        {{- if .Values.deployment.autoRestartOnConfigChange }}
        # Add checksums only when auto-restart is enabled
        # Checksums for core configuration 
        checksum/config: {{ .Values.config.logLevel }}-{{ .Values.config.databaseManagement }}-{{ .Values.config.extraEnvVars | toJson | sha256sum }}
        {{- if .Values.preconfig.enabled }}
        # Checksum for preconfigured database connections
        checksum/preconfig: {{ .Values.preconfig.databases | sha256sum }}
        {{- end }}
        {{- if .Values.passwordEncryption.enabled }}
        # Checksum for encryption secret
        checksum/encryption: {{ .Values.passwordEncryption.enabled | toString | sha256sum }}
        {{- end }}
        {{- if .Values.ingress.basicauth.enabled }}
        # Checksum for basic auth configuration
        checksum/basicauth: {{ .Values.ingress.basicauth.users | toJson | sha256sum }}
        {{- end }}
        {{- end }}
        {{- with .Values.podAnnotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      labels:
        {{- include "redisinsight.labels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "redisinsight.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      initContainers:
        {{- if .Values.persistence.enabled }}
        - name: init-permissions
          image: busybox
          command:
            - /bin/sh
            - '-c'
            - |
              chown -R 1000 /data
          volumeMounts:
            - name: redisinsight-data
              mountPath: /data
        {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: RI_APP_PORT
              value: "{{ .Values.service.port }}"
            - name: RI_APP_HOST
              value: "0.0.0.0"
            {{- if .Values.passwordEncryption.enabled }}
            - name: RI_ENCRYPTION_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ include "redisinsight.fullname" . }}-encryption
                  key: encryptionKey
            {{- end }}
            {{- if .Values.preconfig.enabled }}
            - name: RI_PRE_SETUP_DATABASES_PATH
              value: "/etc/redisinsight/preconfig/preconfig.json"
            {{- end }}
            - name: RI_LOG_LEVEL
              value: "{{ .Values.config.logLevel }}"
            - name: RI_DATABASE_MANAGEMENT
              value: "{{ .Values.config.databaseManagement }}"
            - name: RI_FILES_LOGGER
              value: "true"
            - name: RI_STDOUT_LOGGER
              value: "true"
            {{- with .Values.config.extraEnvVars }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          livenessProbe:
            {{- toYaml .Values.livenessProbe | nindent 12 }}
          readinessProbe:
            {{- toYaml .Values.readinessProbe | nindent 12 }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            {{- if .Values.persistence.enabled }}
            - name: redisinsight-data
              mountPath: /data
            {{- end }}
            {{- if .Values.preconfig.enabled }}
            - name: preconfig-json
              mountPath: /etc/redisinsight/preconfig
              readOnly: true
            {{- end }}
            {{- with .Values.volumeMounts }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
      volumes:
        {{- if .Values.persistence.enabled }}
        - name: redisinsight-data
          persistentVolumeClaim:
            claimName: {{ include "redisinsight.fullname" . }}-data
        {{- end }}
        {{- if .Values.preconfig.enabled }}
        - name: preconfig-json
          secret:
            {{- if .Values.preconfig.existingSecret }}
            secretName: {{ .Values.preconfig.existingSecret }}
            {{- else }}
            secretName: {{ include "redisinsight.fullname" . }}-preconfig
            {{- end }}
            defaultMode: 0444
        {{- end }}
        {{- with .Values.volumes }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
