apiVersion: v1
kind: Secret
metadata:
  name: {{ include "redisinsight.fullname" . }}-preconfig
  labels:
    {{- include "redisinsight.labels" . | nindent 4 }}
type: Opaque
{{- if .Values.preconfig.existingSecret }}
# Use existing secret
{{- else }}
stringData:
  preconfig.json: |-
    {{- .Values.preconfig.databases | nindent 4 }}
{{- end }} 