{{- if and .Values.ingress.enabled .Values.ingress.basicauth.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "redisinsight.fullname" . }}-basic-auth
  labels:
    {{- include "redisinsight.labels" . | nindent 4 }}
type: Opaque
data:
  auth: {{ include "redisinsight.basicauth" . | b64enc }}
{{- end }} 