{{- if .Values.clustersSetup.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "redisinsight.fullname" . }}-setup-clusters-script
  labels:
    {{- include "redisinsight.labels" . | nindent 4 }}
data:
  add-redis-clusters.sh: |-
{{ tpl (.Files.Get "files/redisinsight-init-script.sh") . | indent 4 }}
{{- end }}

