{{- if .Values.clustersSetup.enabled }}
{{- if not .Values.clustersSetup.config.existingSecretConfig }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "redisinsight.fullname" . }}-redis-clusters
  labels:
    {{- include "redisinsight.labels" . | nindent 4 }}
type: Opaque
stringData:
  clusters.json: |-
    {
      {{- $clusterCount := len .Values.clustersSetup.config.redisClusters }}
      {{- range $index, $cluster := .Values.clustersSetup.config.redisClusters }}
      "{{ $cluster.name }}": {{ $cluster | toJson }}{{ if lt $index (sub $clusterCount 1) }},{{ end }}
      {{- end }}
    } 
{{- end }}
{{- end }}