name: Setup GitHub Pages

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - add-ci
    paths:
      - '.github/workflows/pages.yml'

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        
      - name: Setup Pages
        uses: actions/configure-pages@v3
        
      - name: Setup Helm
        uses: azure/setup-helm@v3
        with:
          version: 'v3.11.2'
          
      - name: Create gh-pages Branch if Not Exists
        run: |
          if ! git ls-remote --heads origin gh-pages | grep gh-pages; then
            git checkout --orphan gh-pages
            git rm -rf .
            echo "# Helm Chart Repository" > README.md
            git add README.md
            git config --global user.name "${{ github.actor }}"
            git config --global user.email "${{ github.actor }}@users.noreply.github.com"
            git commit -m "Initial commit"
            git push origin gh-pages
          fi
          
      - name: Build with Jekyll
        run: |
          mkdir -p _site
          echo "# RedisInsight Secure Helm Repository" > _site/index.md
          echo "" >> _site/index.md
          echo "To add this repository to your Helm client:" >> _site/index.md
          echo '```bash' >> _site/index.md
          echo "helm repo add redisinsight-secure https://$(echo ${{ github.repository_owner }}).github.io/$(echo ${{ github.repository }} | cut -d '/' -f 2)/" >> _site/index.md
          echo "helm repo update" >> _site/index.md
          echo '```' >> _site/index.md
          
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v2
        
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2 