name: Release Helm Chart

on:
  push:
    branches:
      - main
      - add-ci
    paths-ignore:
      - 'README.md'
      - '.github/**'
      - '.vscode/**'

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "${{ github.actor }}"
          git config user.email "${{ github.actor }}@users.noreply.github.com"

      - name: Install Helm
        uses: azure/setup-helm@v3
        with:
          version: 'v3.11.2'

      - name: Get Next Version from Conventional Commits
        id: get-version
        uses: mathieudutour/github-tag-action@v6.1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          default_bump: patch
          release_branches: main
          dry_run: true
          tag_prefix: ""

      - name: Update Chart Version
        run: |
          VERSION=${{ steps.get-version.outputs.new_version }}
          echo "Updating chart version to $VERSION"
          sed -i "s/^version: .*/version: $VERSION/" Chart.yaml

      - name: Update App Version
        run: |
          # Optional: Update appVersion if needed
          # This step depends on how you want to handle appVersion
          # APP_VERSION=$(echo ${{ steps.get-version.outputs.new_tag }} | sed 's/v//')
          # sed -i "s/^appVersion: .*/appVersion: \"$APP_VERSION\"/" Chart.yaml

      - name: Package Helm Chart
        run: |
          mkdir -p .cr-release-packages
          helm package . -d .cr-release-packages

      - name: Setup GitHub Pages
        id: pages
        uses: actions/configure-pages@v3

      - name: Upload GitHub Pages artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: '.cr-release-packages'

      - name: Deploy GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2

      - name: Create Release
        uses: mathieudutour/github-tag-action@v6.1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          default_bump: patch
          release_branches: main
          create_annotated_tag: true
          tag_prefix: ""
          dry_run: false

      - name: Update Index.yaml and Push to gh-pages
        run: |
          git checkout gh-pages || git checkout -b gh-pages
          cp -r .cr-release-packages/* .
          helm repo index . --url https://${{ github.repository_owner }}.github.io/$(echo "${{ github.repository }}" | cut -d '/' -f 2)
          
          git add .
          git commit -m "Release ${{ steps.get-version.outputs.new_version }}"
          git push origin gh-pages 